const ORIGO_WEBPUSH_SERVICES_API_BASE_PATH ='/origo/webpush/';

export const environment = {
  GET_TOKEN_DETAILS: ORIGO_WEBPUSH_SERVICES_API_BASE_PATH + "authenticate",
  PROVISIONING: ORIGO_WEBPUSH_SERVICES_API_BASE_PATH + "v2/provision",
  PLATFORMS: ORIGO_WEBPUSH_SERVICES_API_BASE_PATH + "v2/platforms",
  APPLICATION_DETAILS: ORIGO_WEBPUSH_SERVICES_API_BASE_PATH + 'get-details'
};